### ISSUE TITLE
[Bug]: vLLM openai api_server errors out when stream=True

### ISSUE THREAD

**Issue by tstescoTT** [tenstorrent/vllm#31]
### Your current environment

Collecting environment information...
INFO 10-29 18:55:44 importing.py:10] Triton not installed; certain GPU-related functions will not be available.
PyTorch version: 2.2.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Sep 11 2024, 16:02:53)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-193-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 57 bits virtual
CPU(s):                             32
On-line CPU(s) list:                0-31
Thread(s) per core:                 2
Core(s) per socket:                 8
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              106
Model name:                         Intel(R) Xeon(R) Silver 4309Y CPU @ 2.80GHz
Stepping:                           6
Frequency boost:                    enabled
CPU MHz:                            1002.768
CPU max MHz:                        3600.0000
CPU min MHz:                        800.0000
BogoMIPS:                           5600.00
Virtualization:                     VT-x
L1d cache:                          768 KiB
L1i cache:                          512 KiB
L2 cache:                           20 MiB
L3 cache:                           24 MiB
NUMA node0 CPU(s):                  0-7,16-23
NUMA node1 CPU(s):                  8-15,24-31
Vulnerability Gather data sampling: Mitigation; Microcode
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] mypy==1.9.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] pyzmq==26.2.0
[pip3] torch==2.2.1+cpu
[pip3] torch-fidelity==0.3.0
[pip3] torchmetrics==1.3.1
[pip3] torchvision==0.17.1+cpu
[pip3] transformers==4.45.2
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.5@3aae81b59386f6fead4d1195b7a23a4665741c03
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect

### 🐛 Describe the bug

Versions:
- vLLM branch: [dev](https://github.com/tenstorrent/vllm/tree/dev) (last verified commit: [fb458d0](https://github.com/tenstorrent/vllm/tree/fb458d0ab408326ec8fea2958d5b32b5b321877c))
- tt-metal branch: [main](https://github.com/tenstorrent/tt-metal) (last verified commit: [685ef13](https://github.com/tenstorrent/tt-metal/tree/685ef1303b5abdfda63183fdd4fd6ed51b496833))

Streaming is a client side option (https://platform.openai.com/docs/api-reference/streaming)

for example when calling the vLLM AP viaI:
```python
import requests
API_URL = "http://127.0.0.1:8000/v1/completions"
stream = True
prompt = "test 123"
json_data = {
    "model": "meta-llama/Meta-Llama-3.1-70B",
    "prompt": prompt,
    "temperature": 1,
    "top_k": 20,
    "top_p": 0.9,
    "max_tokens": 2048,
    "stream": stream,
    "stop": ["<|eot_id|>"],
}
response = requests.post(API_URL, json=json_data, stream=stream, timeout=600)
```

I get the following error:
```log
$ python examples/server_example_tt.py 
2024-10-28 14:20:29.525 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:329 - Finished prefill for all users up to 16 tokens, Starting decode...  [1147/46204]
INFO 10-28 14:20:29 tt_model_runner.py:376] Capturing trace for first decode execution            
2024-10-28 14:20:50.083 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:capture_trace:173 - Done Capturing Decode Trace   
ERROR 10-28 14:20:50 engine.py:159] TypeError('len() of a 0-d tensor')
ERROR 10-28 14:20:50 engine.py:159] Traceback (most recent call last):
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 157, in start          
ERROR 10-28 14:20:50 engine.py:159]     self.run_engine_loop()        
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 220, in run_engine_loop
ERROR 10-28 14:20:50 engine.py:159]     request_outputs = self.engine_step()
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 238, in engine_step    
ERROR 10-28 14:20:50 engine.py:159]     raise e        
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 229, in engine_step    
ERROR 10-28 14:20:50 engine.py:159]     return self.engine.step()     
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/engine/llm_engine.py", line 1402, in step       
ERROR 10-28 14:20:50 engine.py:159]     outputs = self.model_executor.execute_model(              
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/executor/tt_executor.py", line 55, in execute_model            
ERROR 10-28 14:20:50 engine.py:159]     output = self.driver_worker.execute_model(execute_model_req)             
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/worker/tt_worker.py", line 366, in execute_model
ERROR 10-28 14:20:50 engine.py:159]     output = self.model_runner.execute_model(  
ERROR 10-28 14:20:50 engine.py:159]   File "/tt-metal/python_env/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context          
ERROR 10-28 14:20:50 engine.py:159]     return func(*args, **kwargs)  
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/worker/tt_model_runner.py", line 283, in execute_model         
ERROR 10-28 14:20:50 engine.py:159]     next_token_ids = self._execute_model_single_step(model_input, kv_caches, is_decode, async_out_proc_per_trace, step_idx=i)
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/worker/tt_model_runner.py", line 404, in _execute_model_single_step
ERROR 10-28 14:20:50 engine.py:159]     self._send_async_out(sampler_output, model_input.async_callback, is_first_step_output=(step_idx == 1))    
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/worker/tt_model_runner.py", line 342, in _send_async_out       
ERROR 10-28 14:20:50 engine.py:159]     async_callback()  # trigger output processor              
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/utils.py", line 1135, in weak_bound             
ERROR 10-28 14:20:50 engine.py:159]     unbound(inst, *args, **kwargs)
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/engine/llm_engine.py", line 1189, in _process_model_outputs
ERROR 10-28 14:20:50 engine.py:159]     request_output = RequestOutputFactory.create(
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/outputs.py", line 319, in create
ERROR 10-28 14:20:50 engine.py:159]     return RequestOutput.from_seq_group(seq_group, use_cache)
ERROR 10-28 14:20:50 engine.py:159]   File "/home/user/vllm/vllm/outputs.py", line 166, in from_seq_group
ERROR 10-28 14:20:50 engine.py:159]     int) else len(output_token_ids)
ERROR 10-28 14:20:50 engine.py:159]   File "/tt-metal/python_env/lib/python3.8/site-packages/torch/_tensor.py", line 1000, in __len__
ERROR 10-28 14:20:50 engine.py:159]     raise TypeError("len() of a 0-d tensor")
ERROR 10-28 14:20:50 engine.py:159] TypeError: len() of a 0-d tensor
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/tt-metal/python_env/lib/python3.8/site-packages/starlette/responses.py", line 257, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/tt-metal/python_env/lib/python3.8/site-packages/starlette/responses.py", line 253, in wrap
    await func()
  File "/tt-metal/python_env/lib/python3.8/site-packages/starlette/responses.py", line 230, in listen_for_disconnect
    message = await receive()
  File "/tt-metal/python_env/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/usr/lib/python3.8/asyncio/locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError  
```

Running the async server offline an error also occurs, likely the same one but Engine loop logs aren't displayed:
```log
$ python examples/offline_inference_tt.py --async_engine --max_tokens 2048
...
2024-10-28 14:44:45.212 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 14
2024-10-28 14:44:45.355 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 15
2024-10-28 14:44:45.499 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 16
ERROR 10-28 14:44:45 client.py:250] RuntimeError('Engine loop has died')
ERROR 10-28 14:44:45 client.py:250] Traceback (most recent call last):  
ERROR 10-28 14:44:45 client.py:250]   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 150, in run_heartbeat_loop
ERROR 10-28 14:44:45 client.py:250]     await self._check_success(
ERROR 10-28 14:44:45 client.py:250]   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 314, in _check_success    
ERROR 10-28 14:44:45 client.py:250]     raise response
ERROR 10-28 14:44:45 client.py:250] RuntimeError: Engine loop has died  
2024-10-28 14:44:45.642 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 17
2024-10-28 14:44:45.786 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 18
...
2024-10-28 14:44:47.652 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 31
2024-10-28 14:44:47.796 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:315 - Filling kv cache for user 32
2024-10-28 14:44:47.939 | INFO     | tt_metal.models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:329 - Finished prefill for all users up to 48 tokens, Starting decode...
INFO 10-28 14:44:47 tt_model_runner.py:376] Capturing trace for first decode execution           
Traceback (most recent call last):          
  File "examples/offline_inference_tt.py", line 172, in <module>          
    run_inference(   
  File "examples/offline_inference_tt.py", line 93, in run_inference      
    uvloop.run(_run_inference_async())      
  File "/tt-metal/python_env/lib/python3.8/site-packages/uvloop/__init__.py", line 82, in run    
    return loop.run_until_complete(wrapper())              
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete       
  File "/tt-metal/python_env/lib/python3.8/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "examples/offline_inference_tt.py", line 90, in _run_inference_async       
    await generate_tokens_async(llm, prompts, sampling_params, print_output=True) 
  File "examples/offline_inference_tt.py", line 154, in generate_tokens_async     
    async for i, res in all_gens:           
  File "/home/user/vllm/vllm/utils.py", line 506, in merge_async_iterators
    item = await d   
  File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 598, in _process_request    
    raise request_output
vllm.engine.multiprocessing.MQEngineDeadError: Engine loop is not running. Inspect the stacktrace to find the original error: RuntimeError('Engine loop has died').
(python_env) user@40840e6a0980:~/vllm$ /usr/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '   
```

Last working commit is before oct 17th upstream pulled changes: [3aae81b59386f6fead4d1195b7a23a4665741c03](https://github.com/tenstorrent/vllm/commit/3aae81b59386f6fead4d1195b7a23a4665741c03)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by tstescoTT** [comment]
I was able to reproduce this issue when using `unittest.mock.patch` to mock TTWorker, TTCacheEngine, and TTLlamaForCausalLM to only output random tensor logits and bypass using the TT device. 
```
    |   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 598, in _process_request
    |     raise request_output                                                                             
    |   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 598, in _process_request      
    |     raise request_output                                                                             
    |   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 598, in _process_request                                                                                                                    
    |     raise request_output                                                                             
    |   [Previous line repeated 29 more times]                                                                                                                                                                         
    | TypeError: len() of a 0-d tensor 
```

**Comment by tstescoTT** [comment]
at https://github.com/vllm-project/vllm/blob/main/vllm/sequence.py#L557 
```
(Pdb) seq.data._cached_all_token_ids
[128000, 3923, 527, 279, 5144, 315, 1063, 11495, 20142, 430, 3940, 872, 31133, 389, 37776, 30, tensor(118297)]
(Pdb) seq.data._cached_all_token_ids[-1]
tensor(118297)
(Pdb) len(seq.data._cached_all_token_ids[-1])
*** TypeError: len() of a 0-d tensor
```

It seems the tokens are being returned as 0-d tensors when ints are expected.
