### ISSUE TITLE
[Bug]: online server fails when prompts with greater context than 2048 are sent.

### ISSUE THREAD

**Issue by tstescoTT** [tenstorrent/vllm#35]
### Your current environment

versions:
tt-metal: https://github.com/tenstorrent/tt-metal/commit/385904186f81
vllm: https://github.com/tenstorrent/vllm/commit/384f1790c3be16e1d1b10de07252be2e66d00935

docker container: https://github.com/tenstorrent/tt-inference-server/pkgs/container/tt-inference-server%2Ftt-metal-llama3-70b-src-base-vllm

### 🐛 Describe the bug

run online vLLM server via: https://github.com/tenstorrent/tt-inference-server/blob/main/vllm-tt-metal-llama3-70b/src/run_vllm_api_server.py
```bash
python run_vllm_api_server.py
```

args are the same as: https://github.com/tenstorrent/vllm/blob/dev/examples/server_example_tt.py

```
    # vLLM CLI arguments
    args = {
        "model": "meta-llama/Meta-Llama-3.1-70B",
        "block_size": "64",
        "max_num_seqs": "32",
        "max_model_len": "131072",
        "max_num_batched_tokens": "131072",
        "num_scheduler_steps": "10",
        "port": os.getenv("SERVICE_PORT", "8000"),
        "download-dir": os.getenv("CACHE_DIR", None),
        "api-key": get_encoded_api_key(os.getenv("JWT_SECRET", None)),
    }
```

Once the server starts, send request via HTTP, send prompts greater than 2048 tokens (less than 4096):

vLLM logs:
```log
2024-11-12 21:18:20.650 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:330 - Finished prefill for all users up to 2896 tokens, Starting decode...
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-b2841108cc9d4e7da04186ae33c213ac-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-bcb71e7da3cf4724b9dc90db2afabce2-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-e871d77d6b02420dbdb856b7dc77ad60-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-c04efd556ee9497a9377d715127b3a45-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-e98844a650894a2ca3139a8278ca5d3b-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-c9cf02bee8fd4494b4684421c33c1105-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-10d18880590443058cabb7399a0677ec-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-0b1aabf35ca04d0a9e37c6ba81487e80-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-c4585afb26ac45f7a2257944b3a2001c-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-a2c294b1de2046b7abdeaf0e0b2bac5f-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-7cc652104d24400f9ec61c39c87abc5c-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-16a7d4ace8f648689c8e61dd29efed78-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-4815f5f212724e718774f406a01d48d5-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-b8e00edada534a249fccd6155f612b27-0.
INFO 11-12 21:18:20 engine.py:291] Added request cmpl-b44be65505f349f683149ab23004edbc-0.
2024-11-12 21:18:20.657 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:316 - Filling kv cache for user 1
2024-11-12 21:18:35.000 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:316 - Filling kv cache for user 2
2024-11-12 21:18:46.891 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:316 - Filling kv cache for user 3
2024-11-12 21:18:47.551 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:316 - Filling kv cache for user 4
2024-11-12 21:18:49.178 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:316 - Filling kv cache for user 5
2024-11-12 21:18:49.836 | INFO     | models.demos.t3000.llama2_70b.tt.llama_generation:prefill_forward:316 - Filling kv cache for user 6
ERROR 11-12 21:18:52 client.py:250] RuntimeError('Engine loop has died')
ERROR 11-12 21:18:52 client.py:250] Traceback (most recent call last):
ERROR 11-12 21:18:52 client.py:250]   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 150, in run_heartbeat_loop
ERROR 11-12 21:18:52 client.py:250]     await self._check_success(
ERROR 11-12 21:18:52 client.py:250]   File "/home/user/vllm/vllm/engine/multiprocessing/client.py", line 314, in _check_success
ERROR 11-12 21:18:52 client.py:250]     raise response
ERROR 11-12 21:18:52 client.py:250] RuntimeError: Engine loop has died
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:44624 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44626 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44628 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44636 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44638 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44644 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44648 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44658 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44674 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44690 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44700 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44706 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44716 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44724 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44726 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44730 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:44624 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:44716 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44636 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44690 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44638 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44700 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44626 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44726 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44644 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44730 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44648 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44658 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44706 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44628 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44724 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:44674 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     Shutting down
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:44624 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
CRITICAL 11-12 21:18:52 launcher.py:99] MQLLMEngine is already dead, terminating server process
INFO:     127.0.0.1:44716 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [8]
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by tstescoTT** [comment]
Hypothesis: 
- default `VLLM_RPC_TIMEOUT`=10000 (10,000 ms -> 10 seconds)
- MQLLMEngine last_alive_threshold is set to 3x this (30s default) https://github.com/tenstorrent/vllm/blob/dev/vllm/engine/multiprocessing/engine.py#L118
- MQLLMEngine _heartbeat checks _last_alive_time https://github.com/tenstorrent/vllm/blob/dev/vllm/engine/multiprocessing/engine.py#L325
- _last_alive_time is set by _alive(), this gets called during run_engine_loop() https://github.com/tenstorrent/vllm/blob/dev/vllm/engine/multiprocessing/engine.py#L204
- run_engine_loop() blocks at self.engine_step() for potentially 30+ seconds (e.g. first run, many large prefills) stops _alive() from running
- _heartbeat sends: `RuntimeError("Engine loop has died")`


Possible fix: increase timeout
- set environment variable `VLLM_RPC_TIMEOUT`=100000 (5 minutes total wait time before marking as died)

**Comment by skhorasganiTT** [comment]
I was able to reproduce this with the offline inference test using the command below:
```
WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml python examples/offline_inference_tt.py --measure_perf --async_engine --perf_prompt_len 2896
```
It seems that the async engine's alive loop was being killed due to the prefill compile stage taking too long for the default VLLM_RPC_TIMEOUT, as Tom had hypothesized. Setting it to a higher value like 100000 seems to resolve the issue. 
Tom is going to try verifying this on his end as well.

**Comment by milank94** [comment]
@tstescoTT are you able to validate if this resolved the issue?

**Comment by tstescoTT** [comment]
> [@tstescoTT](https://github.com/tstescoTT) are you able to validate if this resolved the issue?

Increasing the `VLLM_RPC_TIMEOUT` does appear to avoid issues with large batches of prefill happening sequentially and blocking the _alive() loop. I ran over the weekend for a few days with random batch size changes and didn't get any timeouts.

We can close this specific issue. Will open a new one if a different pattern is observed.
